services:
  mongodb-tgs:
    image: mongo:latest
    container_name: mongodb-tgs
    ports:
      - "27020:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ritalidya
      MONGO_INITDB_ROOT_PASSWORD: ritalidya
    networks:
      - network_example
    volumes:
      - "./data-mongo:/data/db"

  mongodb-express-tgs:
    image: mongo-express:latest
    container_name: mongodb-express-tgs
    restart: always
    depends_on:
      - mongodb-tgs
    ports:
      - "8082:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ritalidya
      ME_CONFIG_MONGODB_ADMINPASSWORD: ritalidya
      ME_CONFIG_MONGODB_SERVER: mongodb-tgs
    networks:
      - network_example

networks:
  network_example:
    driver: bridge