services:
  mongodb-prjk:
    image: mongo:latest
    container_name: mongodb-prjk
    restart: always
    ports:
      - "27021:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ritalidya
      MONGO_INITDB_ROOT_PASSWORD: ritalidya
    networks:
      - network_example
    volumes:
      - "./data-mongo:/data/db"
    deploy:
      resources:
        reservations:
          cpus: "0.5"
          memory: 256M
        limits:
          cpus: "1"
          memory: 512M

  mongodb-express-prjk:
    image: mongo-express:latest
    container_name: mongodb-express-prjk
    restart: always
    depends_on:
      - mongodb-prjk
    ports:
      - "8083:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ritalidya
      ME_CONFIG_MONGODB_ADMINPASSWORD: ritalidya
      ME_CONFIG_MONGODB_SERVER: mongodb-prjk
    networks:
      - network_example
    deploy:
      resources:
        reservations:
          cpus: "0.25"
          memory: 50M
        limits:
          cpus: "0.5"
          memory: 100M

networks:
  network_example:
    driver: bridge